// Code generated DO NOT EDIT
// This file was generated by robots at
// 2019-08-26 12:16:30.0516717 -0700 PDT m=+1.514164101
package pom

import (
	"encoding/xml"
	"io"
)

type XMLInner struct {
	InnerXML string `xml:",innerxml"`
}

type XMLAnyElement struct {
	Comment  xml.Comment          `xml:",comment"`
	Elements []XMLAnyElementEntry `xml:",any"`
}

type XMLAnyElementEntry struct {
	XMLName xml.Name
	Value   string      `xml:",chardata"`
	Comment xml.Comment `xml:",comment"`
}

// MarshalXML Remooves the Space field from the XMLName field (Because why does that even exist?)
func (m XMLAnyElementEntry) MarshalXML(e *xml.Encoder, start xml.StartElement) error {

	// Custom marshal is just to get rid of the annoying Space field for XMLName.
	// Converting to a type without a CustomMarshaler so we don't loop forever.
	return e.Encode(xmlMapEntry{XMLName: xml.Name{Local: m.XMLName.Local, Space: ""}, Value: m.Value})
}

// XMLMap is a custom key used to let XML data parse maps
// Because it doesnt do that by default...for some reason.
type XMLMap map[string]string

type xmlMapEntry struct {
	XMLName xml.Name
	Value   string `xml:",chardata"`
}

// MarshalXML marshals the map to XML, with each key in the map being a
// tag and it's corresponding value being it's contents.
func (m XMLMap) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if len(m) == 0 {
		return nil
	}

	err := e.EncodeToken(start)
	if err != nil {
		return err
	}

	for k, v := range m {
		e.Encode(xmlMapEntry{XMLName: xml.Name{Local: k}, Value: v})
	}

	return e.EncodeToken(start.End())
}

// UnmarshalXML takes a key and turns it into a map
func (m *XMLMap) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	*m = XMLMap{}
	for {
		var e xmlMapEntry

		err := d.Decode(&e)
		if err == io.EOF {
			break
		} else if err != nil {
			return err
		}

		(*m)[e.XMLName.Local] = e.Value
	}
	return nil
}

// Sequence Type
type SequenceLicense struct {
	Comment string `xml:",comment"`

	License []*License `xml:"license,omitempty"`
}

func (a *SequenceLicense) GetComment() string {
	return a.Comment
}

func (a *SequenceLicense) GetLicense() []*License {
	if a.License != nil {
		return a.License
	}
	return []*License{}
}

// Sequence Type
type SequenceDeveloper struct {
	Comment string `xml:",comment"`

	Developer []*Developer `xml:"developer,omitempty"`
}

func (a *SequenceDeveloper) GetComment() string {
	return a.Comment
}

func (a *SequenceDeveloper) GetDeveloper() []*Developer {
	if a.Developer != nil {
		return a.Developer
	}
	return []*Developer{}
}

// Sequence Type
type SequenceContributor struct {
	Comment string `xml:",comment"`

	Contributor []*Contributor `xml:"contributor,omitempty"`
}

func (a *SequenceContributor) GetComment() string {
	return a.Comment
}

func (a *SequenceContributor) GetContributor() []*Contributor {
	if a.Contributor != nil {
		return a.Contributor
	}
	return []*Contributor{}
}

// Sequence Type
type SequenceMailingList struct {
	Comment string `xml:",comment"`

	MailingList []*MailingList `xml:"mailingList,omitempty"`
}

func (a *SequenceMailingList) GetComment() string {
	return a.Comment
}

func (a *SequenceMailingList) GetMailingList() []*MailingList {
	if a.MailingList != nil {
		return a.MailingList
	}
	return []*MailingList{}
}

// Sequence Type
type SequenceModule struct {
	Comment string `xml:",comment"`

	Module []*string `xml:"module,omitempty"`
}

func (a *SequenceModule) GetComment() string {
	return a.Comment
}

func (a *SequenceModule) GetModule() []*string {
	if a.Module != nil {
		return a.Module
	}
	return []*string{}
}

// Sequence Type
type SequenceDependency struct {
	Comment string `xml:",comment"`

	Dependency []*Dependency `xml:"dependency,omitempty"`
}

func (a *SequenceDependency) GetComment() string {
	return a.Comment
}

func (a *SequenceDependency) GetDependency() []*Dependency {
	if a.Dependency != nil {
		return a.Dependency
	}
	return []*Dependency{}
}

// Sequence Type
type SequenceRepository struct {
	Comment string `xml:",comment"`

	Repository []*Repository `xml:"repository,omitempty"`
}

func (a *SequenceRepository) GetComment() string {
	return a.Comment
}

func (a *SequenceRepository) GetRepository() []*Repository {
	if a.Repository != nil {
		return a.Repository
	}
	return []*Repository{}
}

// Sequence Type
type SequencePluginRepository struct {
	Comment string `xml:",comment"`

	PluginRepository []*Repository `xml:"pluginRepository,omitempty"`
}

func (a *SequencePluginRepository) GetComment() string {
	return a.Comment
}

func (a *SequencePluginRepository) GetPluginRepository() []*Repository {
	if a.PluginRepository != nil {
		return a.PluginRepository
	}
	return []*Repository{}
}

// Sequence Type
type SequenceProfile struct {
	Comment string `xml:",comment"`

	Profile []*Profile `xml:"profile,omitempty"`
}

func (a *SequenceProfile) GetComment() string {
	return a.Comment
}

func (a *SequenceProfile) GetProfile() []*Profile {
	if a.Profile != nil {
		return a.Profile
	}
	return []*Profile{}
}

// project The <code>&lt;project&gt;</code> element is the root of the descriptor.
//        The following table lists all of the possible child elements.
type project struct {

	/* ModelVersion Declares to which version of project descriptor this POM conforms.*/
	ModelVersion *string `xml:"modelVersion,omitempty"`

	/* Parent The location of the parent project, if one exists. Values from the parent
	   project will be the default for this project if they are left unspecified. The location
	   is given as a group ID, artifact ID and version.*/
	Parent *Parent `xml:"parent,omitempty"`

	/* GroupId A universally unique identifier for a project. It is normal to
	   use a fully-qualified package name to distinguish it from other
	   projects with a similar name (eg. <code>org.apache.maven</code>).*/
	GroupID *string `xml:"groupId,omitempty"`

	/* ArtifactId The identifier for this artifact that is unique within the group given by the
	   group ID. An artifact is something that is either produced or used by a project.
	   Examples of artifacts produced by Maven for a project include: JARs, source and binary
	   distributions, and WARs.*/
	ArtifactID *string `xml:"artifactId,omitempty"`

	/* Version The current version of the artifact produced by this project.*/
	Version *string `xml:"version,omitempty"`

	/* Packaging The type of artifact this project produces, for example <code>jar</code>
	     <code>war</code>
	     <code>ear</code>
	     <code>pom</code>.
	   Plugins can create their own packaging, and
	   therefore their own packaging types,
	   so this list does not contain all possible types.*/
	Packaging *string `xml:"packaging,omitempty"`

	/* Name The full name of the project.*/
	Name *string `xml:"name,omitempty"`

	/* Description A detailed description of the project, used by Maven whenever it needs to
	   describe the project, such as on the web site. While this element can be specified as
	   CDATA to enable the use of HTML tags within the description, it is discouraged to allow
	   plain text representation. If you need to modify the index page of the generated web
	   site, you are able to specify your own instead of adjusting this text.*/
	Description *string `xml:"description,omitempty"`

	/* Url The URL to the project's homepage.
	   <br><b>Default value is</b>: parent value [+ path adjustment] + (artifactId or project.directory property), or just parent value if
	   project's <code>child.project.url.inherit.append.path="false"</code>*/
	URL *string `xml:"url,omitempty"`

	/* InceptionYear The year of the project's inception, specified with 4 digits. This value is
	   used when generating copyright notices as well as being informational.*/
	InceptionYear *string `xml:"inceptionYear,omitempty"`

	/* Organization This element describes various attributes of the organization to which the
	   project belongs. These attributes are utilized when documentation is created (for
	   copyright notices and links).*/
	Organization *Organization `xml:"organization,omitempty"`

	/* Licenses This element describes all of the licenses for this project.
	   Each license is described by a <code>license</code> element, which
	   is then described by additional elements.
	   Projects should only list the license(s) that applies to the project
	   and not the licenses that apply to dependencies.
	   If multiple licenses are listed, it is assumed that the user can select
	   any of them, not that they must accept all.*/
	Licenses *SequenceLicense `xml:"licenses,omitempty"`

	/* Developers Describes the committers of a project.*/
	Developers *SequenceDeveloper `xml:"developers,omitempty"`

	/* Contributors Describes the contributors to a project that are not yet committers.*/
	Contributors *SequenceContributor `xml:"contributors,omitempty"`

	/* MailingLists Contains information about a project's mailing lists.*/
	MailingLists *SequenceMailingList `xml:"mailingLists,omitempty"`

	/* Prerequisites Describes the prerequisites in the build environment for this project.*/
	Prerequisites *Prerequisites `xml:"prerequisites,omitempty"`

	/* Modules The modules (sometimes called subprojects) to build as a part of this
	   project. Each module listed is a relative path to the directory containing the module.
	   To be consistent with the way default urls are calculated from parent, it is recommended
	   to have module names match artifact ids.*/
	Modules *SequenceModule `xml:"modules,omitempty"`

	/* Scm Specification for the SCM used by the project, such as CVS, Subversion, etc.*/
	Scm *Scm `xml:"scm,omitempty"`

	/* IssueManagement The project's issue management system information.*/
	IssueManagement *IssueManagement `xml:"issueManagement,omitempty"`

	/* CiManagement The project's continuous integration information.*/
	CiManagement *CiManagement `xml:"ciManagement,omitempty"`

	/* DistributionManagement Distribution information for a project that enables deployment of the site
	   and artifacts to remote web servers and repositories respectively.*/
	DistributionManagement *DistributionManagement `xml:"distributionManagement,omitempty"`

	/* Properties Properties that can be used throughout the POM as a substitution, and
	   are used as filters in resources if enabled.
	   The format is <code>&lt;name&gt;value&lt;/name&gt;</code>.*/
	Properties *XMLAnyElement `xml:"properties,omitempty"`

	/* DependencyManagement Default dependency information for projects that inherit from this one. The
	   dependencies in this section are not immediately resolved. Instead, when a POM derived
	   from this one declares a dependency described by a matching groupId and artifactId, the
	   version and other values from this section are used for that dependency if they were not
	   already specified.*/
	DependencyManagement *DependencyManagement `xml:"dependencyManagement,omitempty"`

	/* Dependencies This element describes all of the dependencies associated with a
	   project.
	   These dependencies are used to construct a classpath for your
	   project during the build process. They are automatically downloaded from the
	   repositories defined in this project.
	   See <a href="https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html">the
	   dependency mechanism</a> for more information.*/
	Dependencies *SequenceDependency `xml:"dependencies,omitempty"`

	/* Repositories The lists of the remote repositories for discovering dependencies and
	   extensions.*/
	Repositories *SequenceRepository `xml:"repositories,omitempty"`

	/* PluginRepositories The lists of the remote repositories for discovering plugins for builds and
	   reports.*/
	PluginRepositories *SequencePluginRepository `xml:"pluginRepositories,omitempty"`

	/* Build Information required to build the project.*/
	Build *Build `xml:"build,omitempty"`

	/* Reports <b>Deprecated</b>. Now ignored by Maven.*/
	Reports *XMLInner `xml:"reports,omitempty"`

	/* Reporting This element includes the specification of report plugins to use
	   to generate the reports on the Maven-generated site.
	   These reports will be run when a user executes <code>mvn site</code>.
	   All of the reports will be included in the navigation bar for browsing.*/
	Reporting *Reporting `xml:"reporting,omitempty"`

	/* Profiles A listing of project-local build profiles which will modify the build process
	   when activated.*/
	Profiles *SequenceProfile `xml:"profiles,omitempty"`

	Comment string `xml:",comment"`
}

func (a *project) GetModelVersion() string {
	if a.ModelVersion != nil {
		return *a.ModelVersion
	}
	return ""
}

func (a *project) GetParent() Parent {
	if a.Parent != nil {
		return *a.Parent
	}
	return Parent{}
}

func (a *project) GetGroupID() string {
	if a.GroupID != nil {
		return *a.GroupID
	}
	return ""
}

func (a *project) GetArtifactID() string {
	if a.ArtifactID != nil {
		return *a.ArtifactID
	}
	return ""
}

func (a *project) GetVersion() string {
	if a.Version != nil {
		return *a.Version
	}
	return ""
}

func (a *project) GetPackaging() string {
	if a.Packaging != nil {
		return *a.Packaging
	}
	return ""
}

func (a *project) GetName() string {
	if a.Name != nil {
		return *a.Name
	}
	return ""
}

func (a *project) GetDescription() string {
	if a.Description != nil {
		return *a.Description
	}
	return ""
}

func (a *project) GetURL() string {
	if a.URL != nil {
		return *a.URL
	}
	return ""
}

func (a *project) GetInceptionYear() string {
	if a.InceptionYear != nil {
		return *a.InceptionYear
	}
	return ""
}

func (a *project) GetOrganization() Organization {
	if a.Organization != nil {
		return *a.Organization
	}
	return Organization{}
}

func (a *project) GetLicenses() SequenceLicense {
	if a.Licenses != nil {
		return *a.Licenses
	}
	return SequenceLicense{}
}

func (a *project) GetDevelopers() SequenceDeveloper {
	if a.Developers != nil {
		return *a.Developers
	}
	return SequenceDeveloper{}
}

func (a *project) GetContributors() SequenceContributor {
	if a.Contributors != nil {
		return *a.Contributors
	}
	return SequenceContributor{}
}

func (a *project) GetMailingLists() SequenceMailingList {
	if a.MailingLists != nil {
		return *a.MailingLists
	}
	return SequenceMailingList{}
}

func (a *project) GetPrerequisites() Prerequisites {
	if a.Prerequisites != nil {
		return *a.Prerequisites
	}
	return Prerequisites{}
}

func (a *project) GetModules() SequenceModule {
	if a.Modules != nil {
		return *a.Modules
	}
	return SequenceModule{}
}

func (a *project) GetScm() Scm {
	if a.Scm != nil {
		return *a.Scm
	}
	return Scm{}
}

func (a *project) GetIssueManagement() IssueManagement {
	if a.IssueManagement != nil {
		return *a.IssueManagement
	}
	return IssueManagement{}
}

func (a *project) GetCiManagement() CiManagement {
	if a.CiManagement != nil {
		return *a.CiManagement
	}
	return CiManagement{}
}

func (a *project) GetDistributionManagement() DistributionManagement {
	if a.DistributionManagement != nil {
		return *a.DistributionManagement
	}
	return DistributionManagement{}
}

func (a *project) GetProperties() XMLAnyElement {
	if a.Properties != nil {
		return *a.Properties
	}
	return XMLAnyElement{}
}

func (a *project) GetDependencyManagement() DependencyManagement {
	if a.DependencyManagement != nil {
		return *a.DependencyManagement
	}
	return DependencyManagement{}
}

func (a *project) GetDependencies() SequenceDependency {
	if a.Dependencies != nil {
		return *a.Dependencies
	}
	return SequenceDependency{}
}

func (a *project) GetRepositories() SequenceRepository {
	if a.Repositories != nil {
		return *a.Repositories
	}
	return SequenceRepository{}
}

func (a *project) GetPluginRepositories() SequencePluginRepository {
	if a.PluginRepositories != nil {
		return *a.PluginRepositories
	}
	return SequencePluginRepository{}
}

func (a *project) GetBuild() Build {
	if a.Build != nil {
		return *a.Build
	}
	return Build{}
}

func (a *project) GetReports() XMLInner {
	if a.Reports != nil {
		return *a.Reports
	}
	return XMLInner{}
}

func (a *project) GetReporting() Reporting {
	if a.Reporting != nil {
		return *a.Reporting
	}
	return Reporting{}
}

func (a *project) GetProfiles() SequenceProfile {
	if a.Profiles != nil {
		return *a.Profiles
	}
	return SequenceProfile{}
}

func (a *project) GetComment() string {
	return a.Comment
}

// License Describes the licenses for this project. This is used to generate the license
//        page of the project's web site, as well as being taken into consideration in other reporting
//        and validation. The licenses listed for the project are that of the project itself, and not
//        of dependencies.
type License struct {

	/* Name The full legal name of the license.*/
	Name *string `xml:"name,omitempty"`

	/* Url The official url for the license text.*/
	URL *string `xml:"url,omitempty"`

	/* Distribution The primary method by which this project may be distributed.
	   <dl>
	     <dt>repo</dt>
	     <dd>may be downloaded from the Maven repository</dd>
	     <dt>manual</dt>
	     <dd>user must manually download and install the dependency.</dd>
	   </dl>*/
	Distribution *string `xml:"distribution,omitempty"`

	/* Comments Addendum information pertaining to this license.*/
	Comments *string `xml:"comments,omitempty"`

	Comment string `xml:",comment"`
}

func (a *License) GetName() string {
	if a.Name != nil {
		return *a.Name
	}
	return ""
}

func (a *License) GetURL() string {
	if a.URL != nil {
		return *a.URL
	}
	return ""
}

func (a *License) GetDistribution() string {
	if a.Distribution != nil {
		return *a.Distribution
	}
	return ""
}

func (a *License) GetComments() string {
	if a.Comments != nil {
		return *a.Comments
	}
	return ""
}

func (a *License) GetComment() string {
	return a.Comment
}

// Sequence Type
type SequenceNotifier struct {
	Comment string `xml:",comment"`

	Notifier []*Notifier `xml:"notifier,omitempty"`
}

func (a *SequenceNotifier) GetComment() string {
	return a.Comment
}

func (a *SequenceNotifier) GetNotifier() []*Notifier {
	if a.Notifier != nil {
		return a.Notifier
	}
	return []*Notifier{}
}

// CiManagement The <code>&lt;CiManagement&gt;</code> element contains informations required to the
//        continuous integration system of the project.
type CiManagement struct {

	/* System The name of the continuous integration system, e.g. <code>continuum</code>.*/
	System *string `xml:"system,omitempty"`

	/* Url URL for the continuous integration system used by the project if it has a web
	   interface.*/
	URL *string `xml:"url,omitempty"`

	/* Notifiers Configuration for notifying developers/users when a build is unsuccessful,
	   including user information and notification mode.*/
	Notifiers *SequenceNotifier `xml:"notifiers,omitempty"`

	Comment string `xml:",comment"`
}

func (a *CiManagement) GetSystem() string {
	if a.System != nil {
		return *a.System
	}
	return ""
}

func (a *CiManagement) GetURL() string {
	if a.URL != nil {
		return *a.URL
	}
	return ""
}

func (a *CiManagement) GetNotifiers() SequenceNotifier {
	if a.Notifiers != nil {
		return *a.Notifiers
	}
	return SequenceNotifier{}
}

func (a *CiManagement) GetComment() string {
	return a.Comment
}

// Notifier Configures one method for notifying users/developers when a build breaks.
type Notifier struct {

	/* Type The mechanism used to deliver notifications.*/
	Type *string `xml:"type,omitempty"`

	/* SendOnError Whether to send notifications on error.*/
	SendOnError *bool `xml:"sendOnError,omitempty"`

	/* SendOnFailure Whether to send notifications on failure.*/
	SendOnFailure *bool `xml:"sendOnFailure,omitempty"`

	/* SendOnSuccess Whether to send notifications on success.*/
	SendOnSuccess *bool `xml:"sendOnSuccess,omitempty"`

	/* SendOnWarning Whether to send notifications on warning.*/
	SendOnWarning *bool `xml:"sendOnWarning,omitempty"`

	/* Address <b>Deprecated</b>. Where to send the notification to - eg email address.*/
	Address *string `xml:"address,omitempty"`

	/* Configuration Extended configuration specific to this notifier goes here.*/
	Configuration *XMLInner `xml:"configuration,omitempty"`

	Comment string `xml:",comment"`
}

func (a *Notifier) GetType() string {
	if a.Type != nil {
		return *a.Type
	}
	return ""
}

func (a *Notifier) GetSendOnError() bool {
	if a.SendOnError != nil {
		return *a.SendOnError
	}
	return false
}

func (a *Notifier) GetSendOnFailure() bool {
	if a.SendOnFailure != nil {
		return *a.SendOnFailure
	}
	return false
}

func (a *Notifier) GetSendOnSuccess() bool {
	if a.SendOnSuccess != nil {
		return *a.SendOnSuccess
	}
	return false
}

func (a *Notifier) GetSendOnWarning() bool {
	if a.SendOnWarning != nil {
		return *a.SendOnWarning
	}
	return false
}

func (a *Notifier) GetAddress() string {
	if a.Address != nil {
		return *a.Address
	}
	return ""
}

func (a *Notifier) GetConfiguration() XMLInner {
	if a.Configuration != nil {
		return *a.Configuration
	}
	return XMLInner{}
}

func (a *Notifier) GetComment() string {
	return a.Comment
}

// Scm The <code>&lt;scm&gt;</code> element contains informations required to the SCM
//        (Source Control Management) of the project.
type Scm struct {

	/* Connection The source control management system URL
	   that describes the repository and how to connect to the
	   repository. For more information, see the
	   <a href="https://maven.apache.org/scm/scm-url-format.html">URL format</a>
	   and <a href="https://maven.apache.org/scm/scms-overview.html">list of supported SCMs</a>.
	   This connection is read-only.
	   <br><b>Default value is</b>: parent value [+ path adjustment] + (artifactId or project.directory property), or just parent value if
	   scm's <code>child.scm.connection.inherit.append.path="false"</code>*/
	Connection *string `xml:"connection,omitempty"`

	/* DeveloperConnection Just like <code>connection</code>, but for developers, i.e. this scm connection
	   will not be read only.
	   <br><b>Default value is</b>: parent value [+ path adjustment] + (artifactId or project.directory property), or just parent value if
	   scm's <code>child.scm.developerConnection.inherit.append.path="false"</code>*/
	DeveloperConnection *string `xml:"developerConnection,omitempty"`

	/* Tag The tag of current code. By default, it's set to HEAD during development.*/
	Tag *string `xml:"tag,omitempty"`

	/* Url The URL to the project's browsable SCM repository, such as ViewVC or Fisheye.
	   <br><b>Default value is</b>: parent value [+ path adjustment] + (artifactId or project.directory property), or just parent value if
	   scm's <code>child.scm.url.inherit.append.path="false"</code>*/
	URL *string `xml:"url,omitempty"`

	Comment string `xml:",comment"`
}

func (a *Scm) GetConnection() string {
	if a.Connection != nil {
		return *a.Connection
	}
	return ""
}

func (a *Scm) GetDeveloperConnection() string {
	if a.DeveloperConnection != nil {
		return *a.DeveloperConnection
	}
	return ""
}

func (a *Scm) GetTag() string {
	if a.Tag != nil {
		return *a.Tag
	}
	return ""
}

func (a *Scm) GetURL() string {
	if a.URL != nil {
		return *a.URL
	}
	return ""
}

func (a *Scm) GetComment() string {
	return a.Comment
}

// IssueManagement Information about the issue tracking (or bug tracking) system used to manage this
//        project.
type IssueManagement struct {

	/* System The name of the issue management system, e.g. Bugzilla*/
	System *string `xml:"system,omitempty"`

	/* Url URL for the issue management system used by the project.*/
	URL *string `xml:"url,omitempty"`

	Comment string `xml:",comment"`
}

func (a *IssueManagement) GetSystem() string {
	if a.System != nil {
		return *a.System
	}
	return ""
}

func (a *IssueManagement) GetURL() string {
	if a.URL != nil {
		return *a.URL
	}
	return ""
}

func (a *IssueManagement) GetComment() string {
	return a.Comment
}

// DependencyManagement Section for management of default dependency information for use in a group of
//        POMs.
type DependencyManagement struct {

	/* Dependencies The dependencies specified here are not used until they are referenced in a
	   POM within the group. This allows the specification of a "standard" version for a
	   particular dependency.*/
	Dependencies *SequenceDependency `xml:"dependencies,omitempty"`

	Comment string `xml:",comment"`
}

func (a *DependencyManagement) GetDependencies() SequenceDependency {
	if a.Dependencies != nil {
		return *a.Dependencies
	}
	return SequenceDependency{}
}

func (a *DependencyManagement) GetComment() string {
	return a.Comment
}

// Sequence Type
type SequenceExclusion struct {
	Comment string `xml:",comment"`

	Exclusion []*Exclusion `xml:"exclusion,omitempty"`
}

func (a *SequenceExclusion) GetComment() string {
	return a.Comment
}

func (a *SequenceExclusion) GetExclusion() []*Exclusion {
	if a.Exclusion != nil {
		return a.Exclusion
	}
	return []*Exclusion{}
}

// Dependency The <code>&lt;dependency&gt;</code> element contains information about a dependency
//        of the project.
type Dependency struct {

	/* GroupId The project group that produced the dependency, e.g.
	   <code>org.apache.maven</code>.*/
	GroupID *string `xml:"groupId,omitempty"`

	/* ArtifactId The unique id for an artifact produced by the project group, e.g.
	   <code>maven-artifact</code>.*/
	ArtifactID *string `xml:"artifactId,omitempty"`

	/* Version The version of the dependency, e.g. <code>3.2.1</code>. In Maven 2, this can also be
	   specified as a range of versions.*/
	Version *string `xml:"version,omitempty"`

	/* Type The type of dependency. While it
	   usually represents the extension on the filename of the dependency,
	   that is not always the case. A type can be mapped to a different
	   extension and a classifier.
	   The type often corresponds to the packaging used, though this is also
	   not always the case.
	   Some examples are <code>jar</code>, <code>war</code>, <code>ejb-client</code>
	   and <code>test-jar</code>: see <a href="../maven-core/artifact-handlers.html">default
	   artifact handlers</a> for a list.
	   New types can be defined by plugins that set
	   <code>extensions</code> to <code>true</code>, so this is not a complete list.*/
	Type *string `xml:"type,omitempty"`

	/* Classifier The classifier of the dependency. It is appended to
	   the filename after the version. This allows:
	   <ul>
	   <li>referring to attached artifact, for example <code>sources</code> and <code>javadoc</code>:
	   see <a href="../maven-core/artifact-handlers.html">default artifact handlers</a> for a list,</li>
	   <li>distinguishing two artifacts
	   that belong to the same POM but were built differently.
	   For example, <code>jdk14</code> and <code>jdk15</code>.</li>
	   </ul>*/
	Classifier *string `xml:"classifier,omitempty"`

	/* Scope The scope of the dependency - <code>compile</code>, <code>runtime</code>,
	   <code>test</code>, <code>system</code>, and <code>provided</code>. Used to
	   calculate the various classpaths used for compilation, testing, and so on.
	   It also assists in determining which artifacts to include in a distribution of
	   this project. For more information, see
	   <a href="https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html">the
	   dependency mechanism</a>. The default scope is <code>compile</code>.*/
	Scope *string `xml:"scope,omitempty"`

	/* SystemPath FOR SYSTEM SCOPE ONLY. Note that use of this property is <b>discouraged</b>
	   and may be replaced in later versions. This specifies the path on the filesystem
	   for this dependency.
	   Requires an absolute path for the value, not relative.
	   Use a property that gives the machine specific absolute path,
	   e.g. <code>${java.home}</code>.*/
	SystemPath *string `xml:"systemPath,omitempty"`

	/* Exclusions Lists a set of artifacts that should be excluded from this dependency's
	   artifact list when it comes to calculating transitive dependencies.*/
	Exclusions *SequenceExclusion `xml:"exclusions,omitempty"`

	/* Optional Indicates the dependency is optional for use of this library. While the
	   version of the dependency will be taken into account for dependency calculation if the
	   library is used elsewhere, it will not be passed on transitively. Note: While the type
	   of this field is <code>String</code> for technical reasons, the semantic type is actually
	   <code>Boolean</code>. Default value is <code>false</code>.*/
	Optional *string `xml:"optional,omitempty"`

	Comment string `xml:",comment"`
}

func (a *Dependency) GetGroupID() string {
	if a.GroupID != nil {
		return *a.GroupID
	}
	return ""
}

func (a *Dependency) GetArtifactID() string {
	if a.ArtifactID != nil {
		return *a.ArtifactID
	}
	return ""
}

func (a *Dependency) GetVersion() string {
	if a.Version != nil {
		return *a.Version
	}
	return ""
}

func (a *Dependency) GetType() string {
	if a.Type != nil {
		return *a.Type
	}
	return ""
}

func (a *Dependency) GetClassifier() string {
	if a.Classifier != nil {
		return *a.Classifier
	}
	return ""
}

func (a *Dependency) GetScope() string {
	if a.Scope != nil {
		return *a.Scope
	}
	return ""
}

func (a *Dependency) GetSystemPath() string {
	if a.SystemPath != nil {
		return *a.SystemPath
	}
	return ""
}

func (a *Dependency) GetExclusions() SequenceExclusion {
	if a.Exclusions != nil {
		return *a.Exclusions
	}
	return SequenceExclusion{}
}

func (a *Dependency) GetOptional() string {
	if a.Optional != nil {
		return *a.Optional
	}
	return ""
}

func (a *Dependency) GetComment() string {
	return a.Comment
}

// Exclusion The <code>&lt;exclusion&gt;</code> element contains informations required to exclude
//        an artifact to the project.
type Exclusion struct {

	/* ArtifactId The artifact ID of the project to exclude.*/
	ArtifactID *string `xml:"artifactId,omitempty"`

	/* GroupId The group ID of the project to exclude.*/
	GroupID *string `xml:"groupId,omitempty"`

	Comment string `xml:",comment"`
}

func (a *Exclusion) GetArtifactID() string {
	if a.ArtifactID != nil {
		return *a.ArtifactID
	}
	return ""
}

func (a *Exclusion) GetGroupID() string {
	if a.GroupID != nil {
		return *a.GroupID
	}
	return ""
}

func (a *Exclusion) GetComment() string {
	return a.Comment
}

// Parent The <code>&lt;parent&gt;</code> element contains information required to locate the parent project from which
//        this project will inherit from.
//        <strong>Note:</strong> The children of this element are not interpolated and must be given as literal values.
type Parent struct {

	/* GroupId The group id of the parent project to inherit from.*/
	GroupID *string `xml:"groupId,omitempty"`

	/* ArtifactId The artifact id of the parent project to inherit from.*/
	ArtifactID *string `xml:"artifactId,omitempty"`

	/* Version The version of the parent project to inherit.*/
	Version *string `xml:"version,omitempty"`

	/* RelativePath The relative path of the parent <code>pom.xml</code> file within the check out.
	   If not specified, it defaults to <code>../pom.xml</code>.
	   Maven looks for the parent POM first in this location on
	   the filesystem, then the local repository, and lastly in the remote repo.
	   <code>relativePath</code> allows you to select a different location,
	   for example when your structure is flat, or deeper without an intermediate parent POM.
	   However, the group ID, artifact ID and version are still required,
	   and must match the file in the location given or it will revert to the repository for the POM.
	   This feature is only for enhancing the development in a local checkout of that project.
	   Set the value to an empty string in case you want to disable the feature and always resolve
	   the parent POM from the repositories.*/
	RelativePath *string `xml:"relativePath,omitempty"`

	Comment string `xml:",comment"`
}

func (a *Parent) GetGroupID() string {
	if a.GroupID != nil {
		return *a.GroupID
	}
	return ""
}

func (a *Parent) GetArtifactID() string {
	if a.ArtifactID != nil {
		return *a.ArtifactID
	}
	return ""
}

func (a *Parent) GetVersion() string {
	if a.Version != nil {
		return *a.Version
	}
	return ""
}

func (a *Parent) GetRelativePath() string {
	if a.RelativePath != nil {
		return *a.RelativePath
	}
	return ""
}

func (a *Parent) GetComment() string {
	return a.Comment
}

// Sequence Type
type SequenceRole struct {
	Comment string `xml:",comment"`

	Role []*string `xml:"role,omitempty"`
}

func (a *SequenceRole) GetComment() string {
	return a.Comment
}

func (a *SequenceRole) GetRole() []*string {
	if a.Role != nil {
		return a.Role
	}
	return []*string{}
}

// Developer Information about one of the committers on this project.
type Developer struct {

	/* Id The unique ID of the developer in the SCM.*/
	ID *string `xml:"id,omitempty"`

	/* Name The full name of the contributor.*/
	Name *string `xml:"name,omitempty"`

	/* Email The email address of the contributor.*/
	Email *string `xml:"email,omitempty"`

	/* Url The URL for the homepage of the contributor.*/
	URL *string `xml:"url,omitempty"`

	/* Organization The organization to which the contributor belongs.*/
	Organization *string `xml:"organization,omitempty"`

	/* OrganizationUrl The URL of the organization.*/
	OrganizationURL *string `xml:"organizationUrl,omitempty"`

	/* Roles The roles the contributor plays in the project. Each role is described by a
	   <code>role</code> element, the body of which is a role name. This can also be used to
	   describe the contribution.*/
	Roles *SequenceRole `xml:"roles,omitempty"`

	/* Timezone The timezone the contributor is in. Typically, this is a number in the range
	   <a href="http://en.wikipedia.org/wiki/UTC%E2%88%9212:00">-12</a> to <a href="http://en.wikipedia.org/wiki/UTC%2B14:00">+14</a>
	   or a valid time zone id like "America/Montreal" (UTC-05:00) or "Europe/Paris" (UTC+01:00).*/
	Timezone *string `xml:"timezone,omitempty"`

	/* Properties Properties about the contributor, such as an instant messenger handle.*/
	Properties *XMLAnyElement `xml:"properties,omitempty"`

	Comment string `xml:",comment"`
}

func (a *Developer) GetID() string {
	if a.ID != nil {
		return *a.ID
	}
	return ""
}

func (a *Developer) GetName() string {
	if a.Name != nil {
		return *a.Name
	}
	return ""
}

func (a *Developer) GetEmail() string {
	if a.Email != nil {
		return *a.Email
	}
	return ""
}

func (a *Developer) GetURL() string {
	if a.URL != nil {
		return *a.URL
	}
	return ""
}

func (a *Developer) GetOrganization() string {
	if a.Organization != nil {
		return *a.Organization
	}
	return ""
}

func (a *Developer) GetOrganizationURL() string {
	if a.OrganizationURL != nil {
		return *a.OrganizationURL
	}
	return ""
}

func (a *Developer) GetRoles() SequenceRole {
	if a.Roles != nil {
		return *a.Roles
	}
	return SequenceRole{}
}

func (a *Developer) GetTimezone() string {
	if a.Timezone != nil {
		return *a.Timezone
	}
	return ""
}

func (a *Developer) GetProperties() XMLAnyElement {
	if a.Properties != nil {
		return *a.Properties
	}
	return XMLAnyElement{}
}

func (a *Developer) GetComment() string {
	return a.Comment
}

// Sequence Type
type SequenceOtherArchive struct {
	Comment string `xml:",comment"`

	OtherArchive []*string `xml:"otherArchive,omitempty"`
}

func (a *SequenceOtherArchive) GetComment() string {
	return a.Comment
}

func (a *SequenceOtherArchive) GetOtherArchive() []*string {
	if a.OtherArchive != nil {
		return a.OtherArchive
	}
	return []*string{}
}

// MailingList This element describes all of the mailing lists associated with a project. The
//        auto-generated site references this information.
type MailingList struct {

	/* Name The name of the mailing list.*/
	Name *string `xml:"name,omitempty"`

	/* Subscribe The email address or link that can be used to subscribe to
	   the mailing list.  If this is an email address, a
	   <code>mailto:</code> link will automatically be created
	   when the documentation is created.*/
	Subscribe *string `xml:"subscribe,omitempty"`

	/* Unsubscribe The email address or link that can be used to unsubscribe to
	   the mailing list.  If this is an email address, a
	   <code>mailto:</code> link will automatically be created
	   when the documentation is created.*/
	Unsubscribe *string `xml:"unsubscribe,omitempty"`

	/* Post The email address or link that can be used to post to
	   the mailing list.  If this is an email address, a
	   <code>mailto:</code> link will automatically be created
	   when the documentation is created.*/
	Post *string `xml:"post,omitempty"`

	/* Archive The link to a URL where you can browse the mailing list archive.*/
	Archive *string `xml:"archive,omitempty"`

	/* OtherArchives The link to alternate URLs where you can browse the list archive.*/
	OtherArchives *SequenceOtherArchive `xml:"otherArchives,omitempty"`

	Comment string `xml:",comment"`
}

func (a *MailingList) GetName() string {
	if a.Name != nil {
		return *a.Name
	}
	return ""
}

func (a *MailingList) GetSubscribe() string {
	if a.Subscribe != nil {
		return *a.Subscribe
	}
	return ""
}

func (a *MailingList) GetUnsubscribe() string {
	if a.Unsubscribe != nil {
		return *a.Unsubscribe
	}
	return ""
}

func (a *MailingList) GetPost() string {
	if a.Post != nil {
		return *a.Post
	}
	return ""
}

func (a *MailingList) GetArchive() string {
	if a.Archive != nil {
		return *a.Archive
	}
	return ""
}

func (a *MailingList) GetOtherArchives() SequenceOtherArchive {
	if a.OtherArchives != nil {
		return *a.OtherArchives
	}
	return SequenceOtherArchive{}
}

func (a *MailingList) GetComment() string {
	return a.Comment
}

// Contributor Description of a person who has contributed to the project, but who does not have
//        commit privileges. Usually, these contributions come in the form of patches submitted.
type Contributor struct {

	/* Name The full name of the contributor.*/
	Name *string `xml:"name,omitempty"`

	/* Email The email address of the contributor.*/
	Email *string `xml:"email,omitempty"`

	/* Url The URL for the homepage of the contributor.*/
	URL *string `xml:"url,omitempty"`

	/* Organization The organization to which the contributor belongs.*/
	Organization *string `xml:"organization,omitempty"`

	/* OrganizationUrl The URL of the organization.*/
	OrganizationURL *string `xml:"organizationUrl,omitempty"`

	/* Roles The roles the contributor plays in the project. Each role is described by a
	   <code>role</code> element, the body of which is a role name. This can also be used to
	   describe the contribution.*/
	Roles *SequenceRole `xml:"roles,omitempty"`

	/* Timezone The timezone the contributor is in. Typically, this is a number in the range
	   <a href="http://en.wikipedia.org/wiki/UTC%E2%88%9212:00">-12</a> to <a href="http://en.wikipedia.org/wiki/UTC%2B14:00">+14</a>
	   or a valid time zone id like "America/Montreal" (UTC-05:00) or "Europe/Paris" (UTC+01:00).*/
	Timezone *string `xml:"timezone,omitempty"`

	/* Properties Properties about the contributor, such as an instant messenger handle.*/
	Properties *XMLAnyElement `xml:"properties,omitempty"`

	Comment string `xml:",comment"`
}

func (a *Contributor) GetName() string {
	if a.Name != nil {
		return *a.Name
	}
	return ""
}

func (a *Contributor) GetEmail() string {
	if a.Email != nil {
		return *a.Email
	}
	return ""
}

func (a *Contributor) GetURL() string {
	if a.URL != nil {
		return *a.URL
	}
	return ""
}

func (a *Contributor) GetOrganization() string {
	if a.Organization != nil {
		return *a.Organization
	}
	return ""
}

func (a *Contributor) GetOrganizationURL() string {
	if a.OrganizationURL != nil {
		return *a.OrganizationURL
	}
	return ""
}

func (a *Contributor) GetRoles() SequenceRole {
	if a.Roles != nil {
		return *a.Roles
	}
	return SequenceRole{}
}

func (a *Contributor) GetTimezone() string {
	if a.Timezone != nil {
		return *a.Timezone
	}
	return ""
}

func (a *Contributor) GetProperties() XMLAnyElement {
	if a.Properties != nil {
		return *a.Properties
	}
	return XMLAnyElement{}
}

func (a *Contributor) GetComment() string {
	return a.Comment
}

// Organization Specifies the organization that produces this project.
type Organization struct {

	/* Name The full name of the organization.*/
	Name *string `xml:"name,omitempty"`

	/* Url The URL to the organization's home page.*/
	URL *string `xml:"url,omitempty"`

	Comment string `xml:",comment"`
}

func (a *Organization) GetName() string {
	if a.Name != nil {
		return *a.Name
	}
	return ""
}

func (a *Organization) GetURL() string {
	if a.URL != nil {
		return *a.URL
	}
	return ""
}

func (a *Organization) GetComment() string {
	return a.Comment
}

// DistributionManagement This elements describes all that pertains to distribution for a project. It is
//        primarily used for deployment of artifacts and the site produced by the build.
type DistributionManagement struct {

	/* Repository Information needed to deploy the artifacts generated by the project to a
	   remote repository.*/
	Repository *DeploymentRepository `xml:"repository,omitempty"`

	/* SnapshotRepository Where to deploy snapshots of artifacts to. If not given, it defaults to the
	   <code>repository</code> element.*/
	SnapshotRepository *DeploymentRepository `xml:"snapshotRepository,omitempty"`

	/* Site Information needed for deploying the web site of the project.*/
	Site *Site `xml:"site,omitempty"`

	/* DownloadUrl The URL of the project's download page. If not given users will be
	   referred to the homepage given by <code>url</code>.
	   This is given to assist in locating artifacts that are not in the repository due to
	   licensing restrictions.*/
	DownloadURL *string `xml:"downloadUrl,omitempty"`

	/* Relocation Relocation information of the artifact if it has been moved to a new group ID
	   and/or artifact ID.*/
	Relocation *Relocation `xml:"relocation,omitempty"`

	/* Status Gives the status of this artifact in the remote repository.
	   This must not be set in your local project, as it is updated by
	   tools placing it in the reposiory. Valid values are: <code>none</code> (default),
	   <code>converted</code> (repository manager converted this from an Maven 1 POM),
	   <code>partner</code>
	   (directly synced from a partner Maven 2 repository), <code>deployed</code> (was deployed from a Maven 2
	   instance), <code>verified</code> (has been hand verified as correct and final).*/
	Status *string `xml:"status,omitempty"`

	Comment string `xml:",comment"`
}

func (a *DistributionManagement) GetRepository() DeploymentRepository {
	if a.Repository != nil {
		return *a.Repository
	}
	return DeploymentRepository{}
}

func (a *DistributionManagement) GetSnapshotRepository() DeploymentRepository {
	if a.SnapshotRepository != nil {
		return *a.SnapshotRepository
	}
	return DeploymentRepository{}
}

func (a *DistributionManagement) GetSite() Site {
	if a.Site != nil {
		return *a.Site
	}
	return Site{}
}

func (a *DistributionManagement) GetDownloadURL() string {
	if a.DownloadURL != nil {
		return *a.DownloadURL
	}
	return ""
}

func (a *DistributionManagement) GetRelocation() Relocation {
	if a.Relocation != nil {
		return *a.Relocation
	}
	return Relocation{}
}

func (a *DistributionManagement) GetStatus() string {
	if a.Status != nil {
		return *a.Status
	}
	return ""
}

func (a *DistributionManagement) GetComment() string {
	return a.Comment
}

// DeploymentRepository Repository contains the information needed for deploying to the remote
//        repository.
type DeploymentRepository struct {

	/* UniqueVersion Whether to assign snapshots a unique version comprised of the timestamp and
	   build number, or to use the same version each time*/
	UniqueVersion *bool `xml:"uniqueVersion,omitempty"`

	/* Releases How to handle downloading of releases from this repository.*/
	Releases *RepositoryPolicy `xml:"releases,omitempty"`

	/* Snapshots How to handle downloading of snapshots from this repository.*/
	Snapshots *RepositoryPolicy `xml:"snapshots,omitempty"`

	/* Id A unique identifier for a repository. This is used to match the repository
	   to configuration in the <code>settings.xml</code> file, for example. Furthermore, the identifier is
	   used during POM inheritance and profile injection to detect repositories that should be merged.*/
	ID *string `xml:"id,omitempty"`

	/* Name Human readable name of the repository.*/
	Name *string `xml:"name,omitempty"`

	/* Url The url of the repository, in the form <code>protocol://hostname/path</code>.*/
	URL *string `xml:"url,omitempty"`

	/* Layout The type of layout this repository uses for locating and storing artifacts -
	   can be <code>legacy</code> or <code>default</code>.*/
	Layout *string `xml:"layout,omitempty"`

	Comment string `xml:",comment"`
}

func (a *DeploymentRepository) GetUniqueVersion() bool {
	if a.UniqueVersion != nil {
		return *a.UniqueVersion
	}
	return false
}

func (a *DeploymentRepository) GetReleases() RepositoryPolicy {
	if a.Releases != nil {
		return *a.Releases
	}
	return RepositoryPolicy{}
}

func (a *DeploymentRepository) GetSnapshots() RepositoryPolicy {
	if a.Snapshots != nil {
		return *a.Snapshots
	}
	return RepositoryPolicy{}
}

func (a *DeploymentRepository) GetID() string {
	if a.ID != nil {
		return *a.ID
	}
	return ""
}

func (a *DeploymentRepository) GetName() string {
	if a.Name != nil {
		return *a.Name
	}
	return ""
}

func (a *DeploymentRepository) GetURL() string {
	if a.URL != nil {
		return *a.URL
	}
	return ""
}

func (a *DeploymentRepository) GetLayout() string {
	if a.Layout != nil {
		return *a.Layout
	}
	return ""
}

func (a *DeploymentRepository) GetComment() string {
	return a.Comment
}

// RepositoryPolicy Download policy.
type RepositoryPolicy struct {

	/* Enabled Whether to use this repository for downloading this type of artifact. Note: While the type
	   of this field is <code>String</code> for technical reasons, the semantic type is actually
	   <code>Boolean</code>. Default value is <code>true</code>.*/
	Enabled *string `xml:"enabled,omitempty"`

	/* UpdatePolicy The frequency for downloading updates - can be
	   <code>always,</code>
	   <code>daily</code>
	   (default),
	   <code>interval:XXX</code>
	   (in minutes) or
	   <code>never</code>
	   (only if it doesn't exist locally).*/
	UpdatePolicy *string `xml:"updatePolicy,omitempty"`

	/* ChecksumPolicy What to do when verification of an artifact checksum fails. Valid values are
	   <code>ignore</code>
	   ,
	   <code>fail</code>
	   or
	   <code>warn</code>
	   (the default).*/
	ChecksumPolicy *string `xml:"checksumPolicy,omitempty"`

	Comment string `xml:",comment"`
}

func (a *RepositoryPolicy) GetEnabled() string {
	if a.Enabled != nil {
		return *a.Enabled
	}
	return ""
}

func (a *RepositoryPolicy) GetUpdatePolicy() string {
	if a.UpdatePolicy != nil {
		return *a.UpdatePolicy
	}
	return ""
}

func (a *RepositoryPolicy) GetChecksumPolicy() string {
	if a.ChecksumPolicy != nil {
		return *a.ChecksumPolicy
	}
	return ""
}

func (a *RepositoryPolicy) GetComment() string {
	return a.Comment
}

// Relocation Describes where an artifact has moved to. If any of the values are omitted, it is
//        assumed to be the same as it was before.
type Relocation struct {

	/* GroupId The group ID the artifact has moved to.*/
	GroupID *string `xml:"groupId,omitempty"`

	/* ArtifactId The new artifact ID of the artifact.*/
	ArtifactID *string `xml:"artifactId,omitempty"`

	/* Version The new version of the artifact.*/
	Version *string `xml:"version,omitempty"`

	/* Message An additional message to show the user about the move, such as the reason.*/
	Message *string `xml:"message,omitempty"`

	Comment string `xml:",comment"`
}

func (a *Relocation) GetGroupID() string {
	if a.GroupID != nil {
		return *a.GroupID
	}
	return ""
}

func (a *Relocation) GetArtifactID() string {
	if a.ArtifactID != nil {
		return *a.ArtifactID
	}
	return ""
}

func (a *Relocation) GetVersion() string {
	if a.Version != nil {
		return *a.Version
	}
	return ""
}

func (a *Relocation) GetMessage() string {
	if a.Message != nil {
		return *a.Message
	}
	return ""
}

func (a *Relocation) GetComment() string {
	return a.Comment
}

// Site Contains the information needed for deploying websites.
type Site struct {

	/* Id A unique identifier for a deployment location. This is used to match the
	   site to configuration in the <code>settings.xml</code> file, for example.*/
	ID *string `xml:"id,omitempty"`

	/* Name Human readable name of the deployment location.*/
	Name *string `xml:"name,omitempty"`

	/* Url The url of the location where website is deployed, in the form <code>protocol://hostname/path</code>.
	   <br><b>Default value is</b>: parent value [+ path adjustment] + (artifactId or project.directory property), or just parent value if
	   site's <code>child.site.url.inherit.append.path="false"</code>*/
	URL *string `xml:"url,omitempty"`

	Comment string `xml:",comment"`
}

func (a *Site) GetID() string {
	if a.ID != nil {
		return *a.ID
	}
	return ""
}

func (a *Site) GetName() string {
	if a.Name != nil {
		return *a.Name
	}
	return ""
}

func (a *Site) GetURL() string {
	if a.URL != nil {
		return *a.URL
	}
	return ""
}

func (a *Site) GetComment() string {
	return a.Comment
}

// Sequence Type
type SequencePlugin struct {
	Comment string `xml:",comment"`

	Plugin []*ReportPlugin `xml:"plugin,omitempty"`
}

func (a *SequencePlugin) GetComment() string {
	return a.Comment
}

func (a *SequencePlugin) GetPlugin() []*ReportPlugin {
	if a.Plugin != nil {
		return a.Plugin
	}
	return []*ReportPlugin{}
}

// Reporting Section for management of reports and their configuration.
type Reporting struct {

	/* ExcludeDefaults If true, then the default reports are not included in the site generation.
	   This includes the reports in the "Project Info" menu. Note: While the type
	   of this field is <code>String</code> for technical reasons, the semantic type is actually
	   <code>Boolean</code>. Default value is <code>false</code>.*/
	ExcludeDefaults *string `xml:"excludeDefaults,omitempty"`

	/* OutputDirectory Where to store all of the generated reports. The default is
	   <code>${project.build.directory}/site</code>.*/
	OutputDirectory *string `xml:"outputDirectory,omitempty"`

	/* Plugins The reporting plugins to use and their configuration.*/
	Plugins *SequencePlugin `xml:"plugins,omitempty"`

	Comment string `xml:",comment"`
}

func (a *Reporting) GetExcludeDefaults() string {
	if a.ExcludeDefaults != nil {
		return *a.ExcludeDefaults
	}
	return ""
}

func (a *Reporting) GetOutputDirectory() string {
	if a.OutputDirectory != nil {
		return *a.OutputDirectory
	}
	return ""
}

func (a *Reporting) GetPlugins() SequencePlugin {
	if a.Plugins != nil {
		return *a.Plugins
	}
	return SequencePlugin{}
}

func (a *Reporting) GetComment() string {
	return a.Comment
}

// Sequence Type
type SequenceReportSet struct {
	Comment string `xml:",comment"`

	ReportSet []*ReportSet `xml:"reportSet,omitempty"`
}

func (a *SequenceReportSet) GetComment() string {
	return a.Comment
}

func (a *SequenceReportSet) GetReportSet() []*ReportSet {
	if a.ReportSet != nil {
		return a.ReportSet
	}
	return []*ReportSet{}
}

// ReportPlugin The <code>&lt;plugin&gt;</code> element contains informations required for a report plugin.
type ReportPlugin struct {

	/* GroupId The group ID of the reporting plugin in the repository.*/
	GroupID *string `xml:"groupId,omitempty"`

	/* ArtifactId The artifact ID of the reporting plugin in the repository.*/
	ArtifactID *string `xml:"artifactId,omitempty"`

	/* Version The version of the reporting plugin to be used.*/
	Version *string `xml:"version,omitempty"`

	/* ReportSets Multiple specifications of a set of reports, each having (possibly) different
	   configuration. This is the reporting parallel to an <code>execution</code> in the build.*/
	ReportSets *SequenceReportSet `xml:"reportSets,omitempty"`

	/* Inherited Whether any configuration should be propagated to child POMs. Note: While the type
	   of this field is <code>String</code> for technical reasons, the semantic type is actually
	   <code>Boolean</code>. Default value is <code>true</code>.*/
	Inherited *string `xml:"inherited,omitempty"`

	/* Configuration <p>The configuration as DOM object.</p>
	   <p>By default, every element content is trimmed, but starting with Maven 3.1.0, you can add
	   <code>xml:space="preserve"</code> to elements you want to preserve whitespace.</p>
	   <p>You can control how child POMs inherit configuration from parent POMs by adding <code>combine.children</code>
	   or <code>combine.self</code> attributes to the children of the configuration element:</p>
	   <ul>
	   <li><code>combine.children</code>: available values are <code>merge</code> (default) and <code>append</code>,</li>
	   <li><code>combine.self</code>: available values are <code>merge</code> (default) and <code>override</code>.</li>
	   </ul>
	   <p>See <a href="https://maven.apache.org/pom.html#Plugins">POM Reference documentation</a> and
	   <a href="https://codehaus-plexus.github.io/plexus-utils/apidocs/org/codehaus/plexus/util/xml/Xpp3DomUtils.html">Xpp3DomUtils</a>
	   for more information.</p>*/
	Configuration *XMLInner `xml:"configuration,omitempty"`

	Comment string `xml:",comment"`
}

func (a *ReportPlugin) GetGroupID() string {
	if a.GroupID != nil {
		return *a.GroupID
	}
	return ""
}

func (a *ReportPlugin) GetArtifactID() string {
	if a.ArtifactID != nil {
		return *a.ArtifactID
	}
	return ""
}

func (a *ReportPlugin) GetVersion() string {
	if a.Version != nil {
		return *a.Version
	}
	return ""
}

func (a *ReportPlugin) GetReportSets() SequenceReportSet {
	if a.ReportSets != nil {
		return *a.ReportSets
	}
	return SequenceReportSet{}
}

func (a *ReportPlugin) GetInherited() string {
	if a.Inherited != nil {
		return *a.Inherited
	}
	return ""
}

func (a *ReportPlugin) GetConfiguration() XMLInner {
	if a.Configuration != nil {
		return *a.Configuration
	}
	return XMLInner{}
}

func (a *ReportPlugin) GetComment() string {
	return a.Comment
}

// Sequence Type
type SequenceReport struct {
	Comment string `xml:",comment"`

	Report []*string `xml:"report,omitempty"`
}

func (a *SequenceReport) GetComment() string {
	return a.Comment
}

func (a *SequenceReport) GetReport() []*string {
	if a.Report != nil {
		return a.Report
	}
	return []*string{}
}

// ReportSet Represents a set of reports and configuration to be used to generate them.
type ReportSet struct {

	/* Id The unique id for this report set, to be used during POM inheritance and profile injection
	   for merging of report sets.*/
	ID *string `xml:"id,omitempty"`

	/* Reports The list of reports from this plugin which should be generated from this set.*/
	Reports *SequenceReport `xml:"reports,omitempty"`

	/* Inherited Whether any configuration should be propagated to child POMs. Note: While the type
	   of this field is <code>String</code> for technical reasons, the semantic type is actually
	   <code>Boolean</code>. Default value is <code>true</code>.*/
	Inherited *string `xml:"inherited,omitempty"`

	/* Configuration <p>The configuration as DOM object.</p>
	   <p>By default, every element content is trimmed, but starting with Maven 3.1.0, you can add
	   <code>xml:space="preserve"</code> to elements you want to preserve whitespace.</p>
	   <p>You can control how child POMs inherit configuration from parent POMs by adding <code>combine.children</code>
	   or <code>combine.self</code> attributes to the children of the configuration element:</p>
	   <ul>
	   <li><code>combine.children</code>: available values are <code>merge</code> (default) and <code>append</code>,</li>
	   <li><code>combine.self</code>: available values are <code>merge</code> (default) and <code>override</code>.</li>
	   </ul>
	   <p>See <a href="https://maven.apache.org/pom.html#Plugins">POM Reference documentation</a> and
	   <a href="https://codehaus-plexus.github.io/plexus-utils/apidocs/org/codehaus/plexus/util/xml/Xpp3DomUtils.html">Xpp3DomUtils</a>
	   for more information.</p>*/
	Configuration *XMLInner `xml:"configuration,omitempty"`

	Comment string `xml:",comment"`
}

func (a *ReportSet) GetID() string {
	if a.ID != nil {
		return *a.ID
	}
	return ""
}

func (a *ReportSet) GetReports() SequenceReport {
	if a.Reports != nil {
		return *a.Reports
	}
	return SequenceReport{}
}

func (a *ReportSet) GetInherited() string {
	if a.Inherited != nil {
		return *a.Inherited
	}
	return ""
}

func (a *ReportSet) GetConfiguration() XMLInner {
	if a.Configuration != nil {
		return *a.Configuration
	}
	return XMLInner{}
}

func (a *ReportSet) GetComment() string {
	return a.Comment
}

// Profile Modifications to the build process which is activated based on environmental
//        parameters or command line arguments.
type Profile struct {

	/* Id The identifier of this build profile. This is used for command line
	   activation, and identifies profiles to be merged.*/
	ID *string `xml:"id,omitempty"`

	/* Activation The conditional logic which will automatically trigger the inclusion of this
	   profile.*/
	Activation *Activation `xml:"activation,omitempty"`

	/* Build Information required to build the project.*/
	Build *BuildBase `xml:"build,omitempty"`

	/* Modules The modules (sometimes called subprojects) to build as a part of this
	   project. Each module listed is a relative path to the directory containing the module.
	   To be consistent with the way default urls are calculated from parent, it is recommended
	   to have module names match artifact ids.*/
	Modules *SequenceModule `xml:"modules,omitempty"`

	/* DistributionManagement Distribution information for a project that enables deployment of the site
	   and artifacts to remote web servers and repositories respectively.*/
	DistributionManagement *DistributionManagement `xml:"distributionManagement,omitempty"`

	/* Properties Properties that can be used throughout the POM as a substitution, and
	   are used as filters in resources if enabled.
	   The format is <code>&lt;name&gt;value&lt;/name&gt;</code>.*/
	Properties *XMLAnyElement `xml:"properties,omitempty"`

	/* DependencyManagement Default dependency information for projects that inherit from this one. The
	   dependencies in this section are not immediately resolved. Instead, when a POM derived
	   from this one declares a dependency described by a matching groupId and artifactId, the
	   version and other values from this section are used for that dependency if they were not
	   already specified.*/
	DependencyManagement *DependencyManagement `xml:"dependencyManagement,omitempty"`

	/* Dependencies This element describes all of the dependencies associated with a
	   project.
	   These dependencies are used to construct a classpath for your
	   project during the build process. They are automatically downloaded from the
	   repositories defined in this project.
	   See <a href="https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html">the
	   dependency mechanism</a> for more information.*/
	Dependencies *SequenceDependency `xml:"dependencies,omitempty"`

	/* Repositories The lists of the remote repositories for discovering dependencies and
	   extensions.*/
	Repositories *SequenceRepository `xml:"repositories,omitempty"`

	/* PluginRepositories The lists of the remote repositories for discovering plugins for builds and
	   reports.*/
	PluginRepositories *SequencePluginRepository `xml:"pluginRepositories,omitempty"`

	/* Reports <b>Deprecated</b>. Now ignored by Maven.*/
	Reports *XMLInner `xml:"reports,omitempty"`

	/* Reporting This element includes the specification of report plugins to use
	   to generate the reports on the Maven-generated site.
	   These reports will be run when a user executes <code>mvn site</code>.
	   All of the reports will be included in the navigation bar for browsing.*/
	Reporting *Reporting `xml:"reporting,omitempty"`

	Comment string `xml:",comment"`
}

func (a *Profile) GetID() string {
	if a.ID != nil {
		return *a.ID
	}
	return ""
}

func (a *Profile) GetActivation() Activation {
	if a.Activation != nil {
		return *a.Activation
	}
	return Activation{}
}

func (a *Profile) GetBuild() BuildBase {
	if a.Build != nil {
		return *a.Build
	}
	return BuildBase{}
}

func (a *Profile) GetModules() SequenceModule {
	if a.Modules != nil {
		return *a.Modules
	}
	return SequenceModule{}
}

func (a *Profile) GetDistributionManagement() DistributionManagement {
	if a.DistributionManagement != nil {
		return *a.DistributionManagement
	}
	return DistributionManagement{}
}

func (a *Profile) GetProperties() XMLAnyElement {
	if a.Properties != nil {
		return *a.Properties
	}
	return XMLAnyElement{}
}

func (a *Profile) GetDependencyManagement() DependencyManagement {
	if a.DependencyManagement != nil {
		return *a.DependencyManagement
	}
	return DependencyManagement{}
}

func (a *Profile) GetDependencies() SequenceDependency {
	if a.Dependencies != nil {
		return *a.Dependencies
	}
	return SequenceDependency{}
}

func (a *Profile) GetRepositories() SequenceRepository {
	if a.Repositories != nil {
		return *a.Repositories
	}
	return SequenceRepository{}
}

func (a *Profile) GetPluginRepositories() SequencePluginRepository {
	if a.PluginRepositories != nil {
		return *a.PluginRepositories
	}
	return SequencePluginRepository{}
}

func (a *Profile) GetReports() XMLInner {
	if a.Reports != nil {
		return *a.Reports
	}
	return XMLInner{}
}

func (a *Profile) GetReporting() Reporting {
	if a.Reporting != nil {
		return *a.Reporting
	}
	return Reporting{}
}

func (a *Profile) GetComment() string {
	return a.Comment
}

// Activation The conditions within the build runtime environment which will trigger the
//        automatic inclusion of the build profile. Multiple conditions can be defined, which must
//        be all satisfied to activate the profile.
type Activation struct {

	/* ActiveByDefault If set to true, this profile will be active unless another profile in this
	   pom is activated using the command line -P option or by one of that profile's
	   activators.*/
	ActiveByDefault *bool `xml:"activeByDefault,omitempty"`

	/* Jdk Specifies that this profile will be activated when a matching JDK is detected.
	   For example, <code>1.4</code> only activates on JDKs versioned 1.4,
	   while <code>!1.4</code> matches any JDK that is not version 1.4. Ranges are supported too:
	   <code>[1.5,)</code> activates when the JDK is 1.5 minimum.*/
	Jdk *string `xml:"jdk,omitempty"`

	/* Os Specifies that this profile will be activated when matching operating system
	   attributes are detected.*/
	Os *ActivationOS `xml:"os,omitempty"`

	/* Property Specifies that this profile will be activated when this system property is
	   specified.*/
	Property *ActivationProperty `xml:"property,omitempty"`

	/* File Specifies that this profile will be activated based on existence of a file.*/
	File *ActivationFile `xml:"file,omitempty"`

	Comment string `xml:",comment"`
}

func (a *Activation) GetActiveByDefault() bool {
	if a.ActiveByDefault != nil {
		return *a.ActiveByDefault
	}
	return false
}

func (a *Activation) GetJdk() string {
	if a.Jdk != nil {
		return *a.Jdk
	}
	return ""
}

func (a *Activation) GetOs() ActivationOS {
	if a.Os != nil {
		return *a.Os
	}
	return ActivationOS{}
}

func (a *Activation) GetProperty() ActivationProperty {
	if a.Property != nil {
		return *a.Property
	}
	return ActivationProperty{}
}

func (a *Activation) GetFile() ActivationFile {
	if a.File != nil {
		return *a.File
	}
	return ActivationFile{}
}

func (a *Activation) GetComment() string {
	return a.Comment
}

// ActivationProperty This is the property specification used to activate a profile. If the value field
//        is empty, then the existence of the named property will activate the profile, otherwise it
//        does a case-sensitive match against the property value as well.
type ActivationProperty struct {

	/* Name The name of the property to be used to activate a profile.*/
	Name *string `xml:"name,omitempty"`

	/* Value The value of the property required to activate a profile.*/
	Value *string `xml:"value,omitempty"`

	Comment string `xml:",comment"`
}

func (a *ActivationProperty) GetName() string {
	if a.Name != nil {
		return *a.Name
	}
	return ""
}

func (a *ActivationProperty) GetValue() string {
	if a.Value != nil {
		return *a.Value
	}
	return ""
}

func (a *ActivationProperty) GetComment() string {
	return a.Comment
}

// ActivationFile This is the file specification used to activate the profile. The <code>missing</code> value
//        is the location of a file that needs to exist, and if it doesn't, the profile will be
//        activated. On the other hand, <code>exists</code> will test for the existence of the file and if it is
//        there, the profile will be activated.<br>
//        Variable interpolation for these file specifications is limited to <code>${basedir}</code>,
//        System properties and request properties.
type ActivationFile struct {

	/* Missing The name of the file that must be missing to activate the
	   profile.*/
	Missing *string `xml:"missing,omitempty"`

	/* Exists The name of the file that must exist to activate the profile.*/
	Exists *string `xml:"exists,omitempty"`

	Comment string `xml:",comment"`
}

func (a *ActivationFile) GetMissing() string {
	if a.Missing != nil {
		return *a.Missing
	}
	return ""
}

func (a *ActivationFile) GetExists() string {
	if a.Exists != nil {
		return *a.Exists
	}
	return ""
}

func (a *ActivationFile) GetComment() string {
	return a.Comment
}

// ActivationOS This is an activator which will detect an operating system's attributes in order
//        to activate its profile.
type ActivationOS struct {

	/* Name The name of the operating system to be used to activate the profile. This must be an exact match
	   of the <code>${os.name}</code> Java property, such as <code>Windows XP</code>.*/
	Name *string `xml:"name,omitempty"`

	/* Family The general family of the OS to be used to activate the profile, such as
	   <code>windows</code> or <code>unix</code>.*/
	Family *string `xml:"family,omitempty"`

	/* Arch The architecture of the operating system to be used to activate the
	   profile.*/
	Arch *string `xml:"arch,omitempty"`

	/* Version The version of the operating system to be used to activate the
	   profile.*/
	Version *string `xml:"version,omitempty"`

	Comment string `xml:",comment"`
}

func (a *ActivationOS) GetName() string {
	if a.Name != nil {
		return *a.Name
	}
	return ""
}

func (a *ActivationOS) GetFamily() string {
	if a.Family != nil {
		return *a.Family
	}
	return ""
}

func (a *ActivationOS) GetArch() string {
	if a.Arch != nil {
		return *a.Arch
	}
	return ""
}

func (a *ActivationOS) GetVersion() string {
	if a.Version != nil {
		return *a.Version
	}
	return ""
}

func (a *ActivationOS) GetComment() string {
	return a.Comment
}

// Repository A repository contains the information needed for establishing connections with
//        remote repository.
type Repository struct {

	/* Releases How to handle downloading of releases from this repository.*/
	Releases *RepositoryPolicy `xml:"releases,omitempty"`

	/* Snapshots How to handle downloading of snapshots from this repository.*/
	Snapshots *RepositoryPolicy `xml:"snapshots,omitempty"`

	/* Id A unique identifier for a repository. This is used to match the repository
	   to configuration in the <code>settings.xml</code> file, for example. Furthermore, the identifier is
	   used during POM inheritance and profile injection to detect repositories that should be merged.*/
	ID *string `xml:"id,omitempty"`

	/* Name Human readable name of the repository.*/
	Name *string `xml:"name,omitempty"`

	/* Url The url of the repository, in the form <code>protocol://hostname/path</code>.*/
	URL *string `xml:"url,omitempty"`

	/* Layout The type of layout this repository uses for locating and storing artifacts -
	   can be <code>legacy</code> or <code>default</code>.*/
	Layout *string `xml:"layout,omitempty"`

	Comment string `xml:",comment"`
}

func (a *Repository) GetReleases() RepositoryPolicy {
	if a.Releases != nil {
		return *a.Releases
	}
	return RepositoryPolicy{}
}

func (a *Repository) GetSnapshots() RepositoryPolicy {
	if a.Snapshots != nil {
		return *a.Snapshots
	}
	return RepositoryPolicy{}
}

func (a *Repository) GetID() string {
	if a.ID != nil {
		return *a.ID
	}
	return ""
}

func (a *Repository) GetName() string {
	if a.Name != nil {
		return *a.Name
	}
	return ""
}

func (a *Repository) GetURL() string {
	if a.URL != nil {
		return *a.URL
	}
	return ""
}

func (a *Repository) GetLayout() string {
	if a.Layout != nil {
		return *a.Layout
	}
	return ""
}

func (a *Repository) GetComment() string {
	return a.Comment
}

// Sequence Type
type SequenceResource struct {
	Comment string `xml:",comment"`

	Resource []*Resource `xml:"resource,omitempty"`
}

func (a *SequenceResource) GetComment() string {
	return a.Comment
}

func (a *SequenceResource) GetResource() []*Resource {
	if a.Resource != nil {
		return a.Resource
	}
	return []*Resource{}
}

// Sequence Type
type SequenceTestResource struct {
	Comment string `xml:",comment"`

	TestResource []*Resource `xml:"testResource,omitempty"`
}

func (a *SequenceTestResource) GetComment() string {
	return a.Comment
}

func (a *SequenceTestResource) GetTestResource() []*Resource {
	if a.TestResource != nil {
		return a.TestResource
	}
	return []*Resource{}
}

// Sequence Type
type SequenceFilter struct {
	Comment string `xml:",comment"`

	Filter []*string `xml:"filter,omitempty"`
}

func (a *SequenceFilter) GetComment() string {
	return a.Comment
}

func (a *SequenceFilter) GetFilter() []*string {
	if a.Filter != nil {
		return a.Filter
	}
	return []*string{}
}

// BuildBase Generic informations for a build.
type BuildBase struct {

	/* DefaultGoal The default goal (or phase in Maven 2) to execute when none is specified for
	   the project. Note that in case of a multi-module build, only the default goal of the top-level
	   project is relevant, i.e. the default goals of child modules are ignored. Since Maven 3,
	   multiple goals/phases can be separated by whitespace.*/
	DefaultGoal *string `xml:"defaultGoal,omitempty"`

	/* Resources This element describes all of the classpath resources such as properties
	   files associated with a project. These resources are often included in the final
	   package.
	   The default value is <code>src/main/resources</code>.*/
	Resources *SequenceResource `xml:"resources,omitempty"`

	/* TestResources This element describes all of the classpath resources such as properties
	   files associated with a project's unit tests.
	   The default value is <code>src/test/resources</code>.*/
	TestResources *SequenceTestResource `xml:"testResources,omitempty"`

	/* Directory The directory where all files generated by the build are placed.
	   The default value is <code>target</code>.*/
	Directory *string `xml:"directory,omitempty"`

	/* FinalName The filename (excluding the extension, and with no path information) that
	   the produced artifact will be called.
	   The default value is <code>${artifactId}-${version}</code>.*/
	FinalName *string `xml:"finalName,omitempty"`

	/* Filters The list of filter properties files that are used when filtering is enabled.*/
	Filters *SequenceFilter `xml:"filters,omitempty"`

	/* PluginManagement Default plugin information to be made available for reference by projects
	   derived from this one. This plugin configuration will not be resolved or bound to the
	   lifecycle unless referenced. Any local configuration for a given plugin will override
	   the plugin's entire definition here.*/
	PluginManagement *PluginManagement `xml:"pluginManagement,omitempty"`

	/* Plugins The list of plugins to use.*/
	Plugins *SequencePlugin `xml:"plugins,omitempty"`

	Comment string `xml:",comment"`
}

func (a *BuildBase) GetDefaultGoal() string {
	if a.DefaultGoal != nil {
		return *a.DefaultGoal
	}
	return ""
}

func (a *BuildBase) GetResources() SequenceResource {
	if a.Resources != nil {
		return *a.Resources
	}
	return SequenceResource{}
}

func (a *BuildBase) GetTestResources() SequenceTestResource {
	if a.TestResources != nil {
		return *a.TestResources
	}
	return SequenceTestResource{}
}

func (a *BuildBase) GetDirectory() string {
	if a.Directory != nil {
		return *a.Directory
	}
	return ""
}

func (a *BuildBase) GetFinalName() string {
	if a.FinalName != nil {
		return *a.FinalName
	}
	return ""
}

func (a *BuildBase) GetFilters() SequenceFilter {
	if a.Filters != nil {
		return *a.Filters
	}
	return SequenceFilter{}
}

func (a *BuildBase) GetPluginManagement() PluginManagement {
	if a.PluginManagement != nil {
		return *a.PluginManagement
	}
	return PluginManagement{}
}

func (a *BuildBase) GetPlugins() SequencePlugin {
	if a.Plugins != nil {
		return *a.Plugins
	}
	return SequencePlugin{}
}

func (a *BuildBase) GetComment() string {
	return a.Comment
}

// Sequence Type
type SequenceExecution struct {
	Comment string `xml:",comment"`

	Execution []*PluginExecution `xml:"execution,omitempty"`
}

func (a *SequenceExecution) GetComment() string {
	return a.Comment
}

func (a *SequenceExecution) GetExecution() []*PluginExecution {
	if a.Execution != nil {
		return a.Execution
	}
	return []*PluginExecution{}
}

// Plugin The <code>&lt;plugin&gt;</code> element contains informations required for a plugin.
type Plugin struct {

	/* GroupId The group ID of the plugin in the repository.*/
	GroupID *string `xml:"groupId,omitempty"`

	/* ArtifactId The artifact ID of the plugin in the repository.*/
	ArtifactID *string `xml:"artifactId,omitempty"`

	/* Version The version (or valid range of versions) of the plugin to be used.*/
	Version *string `xml:"version,omitempty"`

	/* Extensions Whether to load Maven extensions (such as packaging and type handlers) from
	   this plugin. For performance reasons, this should only be enabled when necessary. Note: While the type
	   of this field is <code>String</code> for technical reasons, the semantic type is actually
	   <code>Boolean</code>. Default value is <code>false</code>.*/
	Extensions *string `xml:"extensions,omitempty"`

	/* Executions Multiple specifications of a set of goals to execute during the build
	   lifecycle, each having (possibly) a different configuration.*/
	Executions *SequenceExecution `xml:"executions,omitempty"`

	/* Dependencies Additional dependencies that this project needs to introduce to the plugin's
	   classloader.*/
	Dependencies *SequenceDependency `xml:"dependencies,omitempty"`

	/* Goals <b>Deprecated</b>. Unused by Maven.*/
	Goals *XMLInner `xml:"goals,omitempty"`

	/* Inherited Whether any configuration should be propagated to child POMs. Note: While the type
	   of this field is <code>String</code> for technical reasons, the semantic type is actually
	   <code>Boolean</code>. Default value is <code>true</code>.*/
	Inherited *string `xml:"inherited,omitempty"`

	/* Configuration <p>The configuration as DOM object.</p>
	   <p>By default, every element content is trimmed, but starting with Maven 3.1.0, you can add
	   <code>xml:space="preserve"</code> to elements you want to preserve whitespace.</p>
	   <p>You can control how child POMs inherit configuration from parent POMs by adding <code>combine.children</code>
	   or <code>combine.self</code> attributes to the children of the configuration element:</p>
	   <ul>
	   <li><code>combine.children</code>: available values are <code>merge</code> (default) and <code>append</code>,</li>
	   <li><code>combine.self</code>: available values are <code>merge</code> (default) and <code>override</code>.</li>
	   </ul>
	   <p>See <a href="https://maven.apache.org/pom.html#Plugins">POM Reference documentation</a> and
	   <a href="https://codehaus-plexus.github.io/plexus-utils/apidocs/org/codehaus/plexus/util/xml/Xpp3DomUtils.html">Xpp3DomUtils</a>
	   for more information.</p>*/
	Configuration *XMLInner `xml:"configuration,omitempty"`

	Comment string `xml:",comment"`
}

func (a *Plugin) GetGroupID() string {
	if a.GroupID != nil {
		return *a.GroupID
	}
	return ""
}

func (a *Plugin) GetArtifactID() string {
	if a.ArtifactID != nil {
		return *a.ArtifactID
	}
	return ""
}

func (a *Plugin) GetVersion() string {
	if a.Version != nil {
		return *a.Version
	}
	return ""
}

func (a *Plugin) GetExtensions() string {
	if a.Extensions != nil {
		return *a.Extensions
	}
	return ""
}

func (a *Plugin) GetExecutions() SequenceExecution {
	if a.Executions != nil {
		return *a.Executions
	}
	return SequenceExecution{}
}

func (a *Plugin) GetDependencies() SequenceDependency {
	if a.Dependencies != nil {
		return *a.Dependencies
	}
	return SequenceDependency{}
}

func (a *Plugin) GetGoals() XMLInner {
	if a.Goals != nil {
		return *a.Goals
	}
	return XMLInner{}
}

func (a *Plugin) GetInherited() string {
	if a.Inherited != nil {
		return *a.Inherited
	}
	return ""
}

func (a *Plugin) GetConfiguration() XMLInner {
	if a.Configuration != nil {
		return *a.Configuration
	}
	return XMLInner{}
}

func (a *Plugin) GetComment() string {
	return a.Comment
}

// Sequence Type
type SequenceGoal struct {
	Comment string `xml:",comment"`

	Goal []*string `xml:"goal,omitempty"`
}

func (a *SequenceGoal) GetComment() string {
	return a.Comment
}

func (a *SequenceGoal) GetGoal() []*string {
	if a.Goal != nil {
		return a.Goal
	}
	return []*string{}
}

// PluginExecution The <code>&lt;execution&gt;</code> element contains informations required for the
//        execution of a plugin.
type PluginExecution struct {

	/* Id The identifier of this execution for labelling the goals during the build,
	   and for matching executions to merge during inheritance and profile injection.*/
	ID *string `xml:"id,omitempty"`

	/* Phase The build lifecycle phase to bind the goals in this execution to. If omitted,
	   the goals will be bound to the default phase specified by the plugin.*/
	Phase *string `xml:"phase,omitempty"`

	/* Goals The goals to execute with the given configuration.*/
	Goals *SequenceGoal `xml:"goals,omitempty"`

	/* Inherited Whether any configuration should be propagated to child POMs. Note: While the type
	   of this field is <code>String</code> for technical reasons, the semantic type is actually
	   <code>Boolean</code>. Default value is <code>true</code>.*/
	Inherited *string `xml:"inherited,omitempty"`

	/* Configuration <p>The configuration as DOM object.</p>
	   <p>By default, every element content is trimmed, but starting with Maven 3.1.0, you can add
	   <code>xml:space="preserve"</code> to elements you want to preserve whitespace.</p>
	   <p>You can control how child POMs inherit configuration from parent POMs by adding <code>combine.children</code>
	   or <code>combine.self</code> attributes to the children of the configuration element:</p>
	   <ul>
	   <li><code>combine.children</code>: available values are <code>merge</code> (default) and <code>append</code>,</li>
	   <li><code>combine.self</code>: available values are <code>merge</code> (default) and <code>override</code>.</li>
	   </ul>
	   <p>See <a href="https://maven.apache.org/pom.html#Plugins">POM Reference documentation</a> and
	   <a href="https://codehaus-plexus.github.io/plexus-utils/apidocs/org/codehaus/plexus/util/xml/Xpp3DomUtils.html">Xpp3DomUtils</a>
	   for more information.</p>*/
	Configuration *XMLInner `xml:"configuration,omitempty"`

	Comment string `xml:",comment"`
}

func (a *PluginExecution) GetID() string {
	if a.ID != nil {
		return *a.ID
	}
	return ""
}

func (a *PluginExecution) GetPhase() string {
	if a.Phase != nil {
		return *a.Phase
	}
	return ""
}

func (a *PluginExecution) GetGoals() SequenceGoal {
	if a.Goals != nil {
		return *a.Goals
	}
	return SequenceGoal{}
}

func (a *PluginExecution) GetInherited() string {
	if a.Inherited != nil {
		return *a.Inherited
	}
	return ""
}

func (a *PluginExecution) GetConfiguration() XMLInner {
	if a.Configuration != nil {
		return *a.Configuration
	}
	return XMLInner{}
}

func (a *PluginExecution) GetComment() string {
	return a.Comment
}

// Sequence Type
type SequenceInclude struct {
	Comment string `xml:",comment"`

	Include []*string `xml:"include,omitempty"`
}

func (a *SequenceInclude) GetComment() string {
	return a.Comment
}

func (a *SequenceInclude) GetInclude() []*string {
	if a.Include != nil {
		return a.Include
	}
	return []*string{}
}

// Sequence Type
type SequenceExclude struct {
	Comment string `xml:",comment"`

	Exclude []*string `xml:"exclude,omitempty"`
}

func (a *SequenceExclude) GetComment() string {
	return a.Comment
}

func (a *SequenceExclude) GetExclude() []*string {
	if a.Exclude != nil {
		return a.Exclude
	}
	return []*string{}
}

// Resource This element describes all of the classpath resources associated with a project
//        or unit tests.
type Resource struct {

	/* TargetPath Describe the resource target path. The path is relative to the target/classes
	   directory (i.e. <code>${project.build.outputDirectory}</code>).
	   For example, if you want that resource to appear in a specific package
	   (<code>org.apache.maven.messages</code>), you must specify this
	   element with this value: <code>org/apache/maven/messages</code>.
	   This is not required if you simply put the resources in that directory
	   structure at the source, however.*/
	TargetPath *string `xml:"targetPath,omitempty"`

	/* Filtering Whether resources are filtered to replace tokens with parameterised values or not.
	   The values are taken from the <code>properties</code> element and from the
	   properties in the files listed in the <code>filters</code> element. Note: While the type
	   of this field is <code>String</code> for technical reasons, the semantic type is actually
	   <code>Boolean</code>. Default value is <code>false</code>.*/
	Filtering *string `xml:"filtering,omitempty"`

	/* Directory Describe the directory where the resources are stored. The path is relative
	   to the POM.*/
	Directory *string `xml:"directory,omitempty"`

	/* Includes A list of patterns to include, e.g. <code>**&#47;*.xml</code>.*/
	Includes *SequenceInclude `xml:"includes,omitempty"`

	/* Excludes A list of patterns to exclude, e.g. <code>**&#47;*.xml</code>*/
	Excludes *SequenceExclude `xml:"excludes,omitempty"`

	Comment string `xml:",comment"`
}

func (a *Resource) GetTargetPath() string {
	if a.TargetPath != nil {
		return *a.TargetPath
	}
	return ""
}

func (a *Resource) GetFiltering() string {
	if a.Filtering != nil {
		return *a.Filtering
	}
	return ""
}

func (a *Resource) GetDirectory() string {
	if a.Directory != nil {
		return *a.Directory
	}
	return ""
}

func (a *Resource) GetIncludes() SequenceInclude {
	if a.Includes != nil {
		return *a.Includes
	}
	return SequenceInclude{}
}

func (a *Resource) GetExcludes() SequenceExclude {
	if a.Excludes != nil {
		return *a.Excludes
	}
	return SequenceExclude{}
}

func (a *Resource) GetComment() string {
	return a.Comment
}

// PluginManagement Section for management of default plugin information for use in a group of POMs.
type PluginManagement struct {

	/* Plugins The list of plugins to use.*/
	Plugins *SequencePlugin `xml:"plugins,omitempty"`

	Comment string `xml:",comment"`
}

func (a *PluginManagement) GetPlugins() SequencePlugin {
	if a.Plugins != nil {
		return *a.Plugins
	}
	return SequencePlugin{}
}

func (a *PluginManagement) GetComment() string {
	return a.Comment
}

// Prerequisites Describes the prerequisites a project can have.
type Prerequisites struct {

	/* Maven For a plugin project (packaging is <code>maven-plugin</code>), the minimum version of
	   Maven required to use the resulting plugin.<br>
	   In Maven 2, this was also specifying the minimum version of Maven required to build a
	   project, but this usage is <b>deprecated</b> in Maven 3 and not checked any more: use
	   the <a href="https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html">Maven Enforcer Plugin's
	   <code>requireMavenVersion</code> rule</a> instead.*/
	Maven *string `xml:"maven,omitempty"`

	Comment string `xml:",comment"`
}

func (a *Prerequisites) GetMaven() string {
	if a.Maven != nil {
		return *a.Maven
	}
	return ""
}

func (a *Prerequisites) GetComment() string {
	return a.Comment
}

// Sequence Type
type SequenceExtension struct {
	Comment string `xml:",comment"`

	Extension []*Extension `xml:"extension,omitempty"`
}

func (a *SequenceExtension) GetComment() string {
	return a.Comment
}

func (a *SequenceExtension) GetExtension() []*Extension {
	if a.Extension != nil {
		return a.Extension
	}
	return []*Extension{}
}

// Build The <code>&lt;build&gt;</code> element contains informations required to build the project.
//        Default values are defined in Super POM.
type Build struct {

	/* SourceDirectory This element specifies a directory containing the source of the project. The
	   generated build system will compile the sources from this directory when the project is
	   built. The path given is relative to the project descriptor.
	   The default value is <code>src/main/java</code>.*/
	SourceDirectory *string `xml:"sourceDirectory,omitempty"`

	/* ScriptSourceDirectory This element specifies a directory containing the script sources of the
	   project. This directory is meant to be different from the sourceDirectory, in that its
	   contents will be copied to the output directory in most cases (since scripts are
	   interpreted rather than compiled).
	   The default value is <code>src/main/scripts</code>.*/
	ScriptSourceDirectory *string `xml:"scriptSourceDirectory,omitempty"`

	/* TestSourceDirectory This element specifies a directory containing the unit test source of the
	   project. The generated build system will compile these directories when the project is
	   being tested. The path given is relative to the project descriptor.
	   The default value is <code>src/test/java</code>.*/
	TestSourceDirectory *string `xml:"testSourceDirectory,omitempty"`

	/* OutputDirectory The directory where compiled application classes are placed.
	   The default value is <code>target/classes</code>.*/
	OutputDirectory *string `xml:"outputDirectory,omitempty"`

	/* TestOutputDirectory The directory where compiled test classes are placed.
	   The default value is <code>target/test-classes</code>.*/
	TestOutputDirectory *string `xml:"testOutputDirectory,omitempty"`

	/* Extensions A set of build extensions to use from this project.*/
	Extensions *SequenceExtension `xml:"extensions,omitempty"`

	/* DefaultGoal The default goal (or phase in Maven 2) to execute when none is specified for
	   the project. Note that in case of a multi-module build, only the default goal of the top-level
	   project is relevant, i.e. the default goals of child modules are ignored. Since Maven 3,
	   multiple goals/phases can be separated by whitespace.*/
	DefaultGoal *string `xml:"defaultGoal,omitempty"`

	/* Resources This element describes all of the classpath resources such as properties
	   files associated with a project. These resources are often included in the final
	   package.
	   The default value is <code>src/main/resources</code>.*/
	Resources *SequenceResource `xml:"resources,omitempty"`

	/* TestResources This element describes all of the classpath resources such as properties
	   files associated with a project's unit tests.
	   The default value is <code>src/test/resources</code>.*/
	TestResources *SequenceTestResource `xml:"testResources,omitempty"`

	/* Directory The directory where all files generated by the build are placed.
	   The default value is <code>target</code>.*/
	Directory *string `xml:"directory,omitempty"`

	/* FinalName The filename (excluding the extension, and with no path information) that
	   the produced artifact will be called.
	   The default value is <code>${artifactId}-${version}</code>.*/
	FinalName *string `xml:"finalName,omitempty"`

	/* Filters The list of filter properties files that are used when filtering is enabled.*/
	Filters *SequenceFilter `xml:"filters,omitempty"`

	/* PluginManagement Default plugin information to be made available for reference by projects
	   derived from this one. This plugin configuration will not be resolved or bound to the
	   lifecycle unless referenced. Any local configuration for a given plugin will override
	   the plugin's entire definition here.*/
	PluginManagement *PluginManagement `xml:"pluginManagement,omitempty"`

	/* Plugins The list of plugins to use.*/
	Plugins *SequencePlugin `xml:"plugins,omitempty"`

	Comment string `xml:",comment"`
}

func (a *Build) GetSourceDirectory() string {
	if a.SourceDirectory != nil {
		return *a.SourceDirectory
	}
	return ""
}

func (a *Build) GetScriptSourceDirectory() string {
	if a.ScriptSourceDirectory != nil {
		return *a.ScriptSourceDirectory
	}
	return ""
}

func (a *Build) GetTestSourceDirectory() string {
	if a.TestSourceDirectory != nil {
		return *a.TestSourceDirectory
	}
	return ""
}

func (a *Build) GetOutputDirectory() string {
	if a.OutputDirectory != nil {
		return *a.OutputDirectory
	}
	return ""
}

func (a *Build) GetTestOutputDirectory() string {
	if a.TestOutputDirectory != nil {
		return *a.TestOutputDirectory
	}
	return ""
}

func (a *Build) GetExtensions() SequenceExtension {
	if a.Extensions != nil {
		return *a.Extensions
	}
	return SequenceExtension{}
}

func (a *Build) GetDefaultGoal() string {
	if a.DefaultGoal != nil {
		return *a.DefaultGoal
	}
	return ""
}

func (a *Build) GetResources() SequenceResource {
	if a.Resources != nil {
		return *a.Resources
	}
	return SequenceResource{}
}

func (a *Build) GetTestResources() SequenceTestResource {
	if a.TestResources != nil {
		return *a.TestResources
	}
	return SequenceTestResource{}
}

func (a *Build) GetDirectory() string {
	if a.Directory != nil {
		return *a.Directory
	}
	return ""
}

func (a *Build) GetFinalName() string {
	if a.FinalName != nil {
		return *a.FinalName
	}
	return ""
}

func (a *Build) GetFilters() SequenceFilter {
	if a.Filters != nil {
		return *a.Filters
	}
	return SequenceFilter{}
}

func (a *Build) GetPluginManagement() PluginManagement {
	if a.PluginManagement != nil {
		return *a.PluginManagement
	}
	return PluginManagement{}
}

func (a *Build) GetPlugins() SequencePlugin {
	if a.Plugins != nil {
		return *a.Plugins
	}
	return SequencePlugin{}
}

func (a *Build) GetComment() string {
	return a.Comment
}

// Extension Describes a build extension to utilise.
type Extension struct {

	/* GroupId The group ID of the extension's artifact.*/
	GroupID *string `xml:"groupId,omitempty"`

	/* ArtifactId The artifact ID of the extension.*/
	ArtifactID *string `xml:"artifactId,omitempty"`

	/* Version The version of the extension.*/
	Version *string `xml:"version,omitempty"`

	Comment string `xml:",comment"`
}

func (a *Extension) GetGroupID() string {
	if a.GroupID != nil {
		return *a.GroupID
	}
	return ""
}

func (a *Extension) GetArtifactID() string {
	if a.ArtifactID != nil {
		return *a.ArtifactID
	}
	return ""
}

func (a *Extension) GetVersion() string {
	if a.Version != nil {
		return *a.Version
	}
	return ""
}

func (a *Extension) GetComment() string {
	return a.Comment
}
