package pom

var examplePom = `<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <artifactId>msods-sync-client</artifactId>
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <compilerArgs>
                        <arg>-Xlint</arg>
                        <arg>-XDignore.symbol.file</arg>
                    </compilerArgs>
                    <encoding>UTF-8</encoding>
                    <fork>true</fork>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
                <groupId>org.apache.maven.plugins</groupId>
                <version>3.1</version>
            </plugin>
            <plugin>
                <artifactId>maven-source-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                        <id>attach-sources</id>
                    </execution>
                </executions>
                <groupId>org.apache.maven.plugins</groupId>
                <version>2.2.1</version>
            </plugin>
            <plugin>
                <artifactId>maven-release-plugin</artifactId>
                <groupId>org.apache.maven.plugins</groupId>
                <version>2.4.1</version>
            </plugin>
            <plugin>
                <artifactId>maven-resources-plugin</artifactId>
                <groupId>org.apache.maven.plugins</groupId>
                <version>2.6</version>
            </plugin>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <groupId>org.apache.maven.plugins</groupId>
                <version>2.16</version>
            </plugin>
            <plugin>
                <artifactId>findbugs-maven-plugin</artifactId>
                <configuration>
                    <effort>Max</effort>
                    <excludeFilterFile>${basedir}/findbugs-exclude.xml</excludeFilterFile>
                    <includeTests>true</includeTests>
                    <threshold>Low</threshold>
                    <xmlOutput>true</xmlOutput>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
                <groupId>org.codehaus.mojo</groupId>
                <version>3.0.1</version>
            </plugin>
            <plugin>
                <!-- Run this plugin after copying over new schema files. NOTE: they require hand-editing
                 for this plugin to succeed. See the README.md of this repo for the wiki on how to do that. -->
                <artifactId>cxf-codegen-plugin</artifactId>
                <executions>
                    <execution>
                        <configuration>
                            <defaultOptions>
                                <bindingFiles>
                                    <!-- These come from the MSODS team -->
                                    <bindingFile>${wsdl.dir}/DirectoryChange.xsd</bindingFile>
                                    <bindingFile>${wsdl.dir}/DirectorySync.xsd</bindingFile>
                                    <bindingFile>${wsdl.dir}/DirectorySync2.xsd</bindingFile>
                                    <bindingFile>${wsdl.dir}/DirectorySyncMetadata.xsd</bindingFile>
                                    <bindingFile>${wsdl.dir}/Serialization.Arrays.xsd</bindingFile>
                                    <bindingFile>${wsdl.dir}/Serialization.xsd</bindingFile>
                                    <bindingFile>${wsdl.dir}/ServiceInstanceMove.xsd</bindingFile>
                                    <bindingFile>${wsdl.dir}/System.xsd</bindingFile>
                                    <bindingFile>${wsdl.dir}/Annotations.xsd</bindingFile>
                                    <!-- This is from the O365 team -->
                                    <bindingFile>${wsdl.dir}/ExtensibilitySchema.xsd</bindingFile>
                                </bindingFiles>
                                <extraargs>
                                    <extraarg>-xjc-npa</extraarg>
                                </extraargs>
                            </defaultOptions>
                            <sourceRoot>${basedir}/target/generated-sources/wsimport</sourceRoot>
                            <wsdlOptions>
                                <wsdlOPtion>
                                    <wsdl>${basedir}/src/main/resources/wsdl-modified/ServiceInstanceMove.wsdl</wsdl>
                                    <wsdlLocation>classpath:wsdl-modified/ServiceInstanceMove.wsdl</wsdlLocation>
                                </wsdlOPtion>
                                <wsdlOPtion>
                                    <wsdl>${basedir}/src/main/resources/wsdl-modified/FederatedServiceOnboarding.wsdl</wsdl>
                                    <wsdlLocation>classpath:wsdl-modified/FederatedServiceOnboarding.wsdl</wsdlLocation>
                                </wsdlOPtion>
                                <wsdlOption>
                                    <wsdl>${basedir}/src/main/resources/wsdl-modified/DirectorySync.wsdl</wsdl>
                                    <wsdlLocation>classpath:wsdl-modified/DirectorySync.wsdl</wsdlLocation>
                                </wsdlOption>
                            </wsdlOptions>
                        </configuration>
                        <goals>
                            <goal>wsdl2java</goal>
                        </goals>
                        <id>generate-sources</id>
                        <phase>generate-sources</phase>
                    </execution>
                </executions>
                <groupId>org.apache.cxf</groupId>
                <version>3.2.6</version>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <artifactId>slf4j-api</artifactId>
            <groupId>org.slf4j</groupId>
            <scope>provided</scope>
            <version>[1.7.6]</version>
        </dependency>
        <dependency>
            <artifactId>commons-codec</artifactId>
            <groupId>commons-codec</groupId>
            <scope>test</scope>
            <version>[1.8]</version>
        </dependency>
        <dependency>
            <artifactId>junit</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>hamcrest-core</artifactId>
                    <groupId>org.hamcrest</groupId>
                </exclusion>
            </exclusions>
            <groupId>junit</groupId>
            <scope>test</scope>
            <version>[4.11]</version>
        </dependency>
        <dependency>
            <artifactId>mockito-all</artifactId>
            <groupId>org.mockito</groupId>
            <scope>test</scope>
            <version>[1.9.5]</version>
        </dependency>
        <dependency>
            <artifactId>assertj-core</artifactId>
            <groupId>org.assertj</groupId>
            <scope>test</scope>
            <version>[1.3.0]</version>
        </dependency>
    </dependencies>
    <distributionManagement>
        <repository>
            <id>dev-azure-com-yammer-yammer-artifacts</id>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
            <url>https://pkgs.dev.azure.com/yammer/_packaging/yammer-artifacts/maven/v1</url>
        </repository>
    </distributionManagement>
    <groupId>com.microsoft.msods</groupId>
    <modelVersion>4.0.0</modelVersion>
    <pluginRepositories>
        <pluginRepository>
            <id>maven.int.yammer.com</id>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
            </snapshots>
            <url>http://maven.int.yammer.com/nexus/content/groups/public/</url>
        </pluginRepository>
    </pluginRepositories>
    <properties>
        <wsdl.dir>${project.basedir}/src/main/resources/${wsdl.dir.name}</wsdl.dir>
        <wsdl.dir.name>wsdl-modified</wsdl.dir.name>
    </properties>
    <repositories>
        <repository>
            <id>dev-azure-com-yammer-yammer-artifacts</id>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
            <url>https://pkgs.dev.azure.com/yammer/_packaging/yammer-artifacts/maven/v1</url>
        </repository>
    </repositories>
    <scm>
        <connection>scm:git:git://github.int.yammer.com/yammer/msods-sync-client.git</connection>
        <developerConnection>scm:git:git@github.int.yammer.com:yammer/msods-sync-client.git</developerConnection>
        <tag>HEAD</tag>
        <url>https://github.int.yammer.com/yammer/msods-sync-client</url>
    </scm>
    <version>0.4.22-SNAPSHOT</version>
</project>`

var reMarshaledPom = `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.microsoft.msods</groupId>
    <artifactId>msods-sync-client</artifactId>
    <version>0.4.22-SNAPSHOT</version>
    <scm>
        <connection>scm:git:git://github.int.yammer.com/yammer/msods-sync-client.git</connection>
        <developerConnection>scm:git:git@github.int.yammer.com:yammer/msods-sync-client.git</developerConnection>
        <tag>HEAD</tag>
        <url>https://github.int.yammer.com/yammer/msods-sync-client</url>
    </scm>
    <distributionManagement>
        <repository>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
            <id>dev-azure-com-yammer-yammer-artifacts</id>
            <url>https://pkgs.dev.azure.com/yammer/_packaging/yammer-artifacts/maven/v1</url>
        </repository>
    </distributionManagement>
    <properties>
        <wsdl.dir>${project.basedir}/src/main/resources/${wsdl.dir.name}</wsdl.dir>
        <wsdl.dir.name>wsdl-modified</wsdl.dir.name>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>[1.7.6]</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
            <version>[1.8]</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>[4.11]</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <artifactId>hamcrest-core</artifactId>
                    <groupId>org.hamcrest</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-all</artifactId>
            <version>[1.9.5]</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>[1.3.0]</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <repositories>
        <repository>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
            <id>dev-azure-com-yammer-yammer-artifacts</id>
            <url>https://pkgs.dev.azure.com/yammer/_packaging/yammer-artifacts/maven/v1</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
            </snapshots>
            <id>maven.int.yammer.com</id>
            <url>http://maven.int.yammer.com/nexus/content/groups/public/</url>
        </pluginRepository>
    </pluginRepositories>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <compilerArgs>
                        <arg>-Xlint</arg>
                        <arg>-XDignore.symbol.file</arg>
                    </compilerArgs>
                    <encoding>UTF-8</encoding>
                    <fork>true</fork>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>2.2.1</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <version>2.4.1</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>2.6</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.16</version>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>findbugs-maven-plugin</artifactId>
                <version>3.0.1</version>
                <configuration>
                    <effort>Max</effort>
                    <excludeFilterFile>${basedir}/findbugs-exclude.xml</excludeFilterFile>
                    <includeTests>true</includeTests>
                    <threshold>Low</threshold>
                    <xmlOutput>true</xmlOutput>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.cxf</groupId>
                <artifactId>cxf-codegen-plugin</artifactId>
                <version>3.2.6</version>
                <!-- Run this plugin after copying over new schema files. NOTE: they require hand-editing
                 for this plugin to succeed. See the README.md of this repo for the wiki on how to do that. -->
            </plugin>
        </plugins>
    </build>
</project>`
